In [2]:
# Install the PyDrive2 wrapper & import libraries.
# This only needs to be done once per notebook.
!pip install -U -q PyDrive2
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [3]:
# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [4]:
# Auto-iterate through all files that matches this query
file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()
for file1 in file_list:
  print('title: %s, id: %s' % (file1['title'], file1['id']))

title: twitter_northeastern, id: 1Cb9wu-L1YfjirEqWCoix-3bDHGIoKGIT
title: Staples Dispute of Mastercard Giftcard Purchase, id: 16XAmM3TW6_mY_io7Y3H8a-VStg5_SMAkDe9Z2q1BfLI
title: Letter of Explanation: Anunya Debt, id: 1vD1Ob86s2AacOFwUzjHodSFHQbvg08ZBJMrS4sUrktI
title: Innovis: Disputing Information in my Credit Report, id: 1i6OWTwCs-iV2nhxdlOJXwyCHq3GhIkpRpgZ0wGv91p0
title: TransUnion: Disputing Information in my Credit Report, id: 10Yz_Na9GsUTWJrbyP3m64l6nYTYNH2DU4dnIR8cJ6Xc
title: Equifax: Disputing Information in my Credit Report, id: 1zJwAxb9yJjTfaFXnaWigcgMcK0iODaaj67iPJ1G_yIQ
title: Experian: Disputing Information in my Credit Report, id: 1bluLCY6TH01gH9-Ed8WRdlA_7di6oAF4SzUz2-1ztoc
title: Letter of Explanation, id: 1rEoRwVmBAhaX2jdpJ7Uy0839qekLcXSUFVrjC9zrxBM
title: My Debt, id: 1gc79HW85bDQvkwPZl_MIe3_A16Opj9FMsiqbp4dPPEc
title: MBA - Copy of Wordboard Doc, id: 12IyN2XSTooqENldIb63wPQSQgLBI79i5kMamr_aSblU
title: Pattra_Pitt_W2_Statement for 2023.pdf, id: 1lgpku_tkhdZUZ4Z5QL4Tf_o5SB5cxvEI
title: Jessica, id: 1M6tKtsH6tojno6CeLRCKOS1nom1H0sqf
title: Plan of Actions, id: 14UxVq4X2y_DYrWomiN7kF4mNgSKKF9Q
title: beyondperk, id: 1rGuZz2kq_TIxz1v-PAufnRHsOtOHf3bz
title: receipt, id: 1l6cdhFVdy5NAHbXkpOD7-4vHpdwmlLGI
title: Pollutant Causal Analysis, id: 1Wbo_DAfgZYE3AVsD6UXFRDSBwYW2Qqc6FFgpz0Y6XOY
title: software, id: 1OnfeoXcQg-mnJoB-pU2H7eu1re8NoASa
title: Coverage by Zipcode, id: 1W6eL9PUivM-Ou2pnDrDvmY4e9TOf8gn7SjeFLLKlFW4
title: tmp, id: 1J95jsa0H-BVoFM0ooFuAJ97glBiTe_N0
title: kayhan, id: 1Ha8MH-UPz0YhGcFcbzoH6b47mzDmN06n
title: publication, id: 1H0minWIayCBu7YSoPRgkN4y7l6CyL_PA
title: wedding, id: 1N4sTWVhb1jkb5ITA6A2BMvwGs3cM38s3
title: greencard, id: 1gudsak9aV01HOWRij7uAJpBf3275_kc7
title: Colab Notebooks, id: 1uj83mBfVHW8bBtiqRahes9ZaXPAHMHFh
title: teaching, id: 1fQjGYzqotOlDPYp6of7jjvNSrZriWfBs
title: 539 Expense, id: 1IteW56JiK5SoINFFyRlWgcQFXiOTzaRBdfhlRxUCMQQ
title: Personal, id: 0B_WF4Yy9mLocTGpDamp0MkFLbW8
title: comet, id: 0B_WF4Yy9mLocQW1tZmxnUEs1Qjg

In [5]:
# Auto-iterate through all files that matches this query
file_list = drive.ListFile({'q': "'1Cb9wu-L1YfjirEqWCoix-3bDHGIoKGIT' in parents and trashed=false"}).GetList()
for file1 in file_list:
  print('title: %s, id: %s' % (file1['title'], file1['id']))

title: summarize_tweets.ipynb, id: 1otAlLol_zSeeQ7gmvYH3Fw5CStEE4_e8
title: IDI Take-Home Task, id: 1f8-GSTrUz5j9G9atRQVbvTNrB3l9BTy7IVhVqppD97o
title: Copy of correct_twitter_201904.tsv, id: 1er3k0HcJPW0U-0U3d7ROzALYmyAv-19G
title: Copy of correct_twitter_202102.tsv, id: 13LSelzc2GIJLFL9-_zsTvf6N6RktOXGc

In [6]:
# Download a file based on its file ID.
# 500MB Copy of correct_twitter_202102.tsv
# A file ID looks like: 13LSelzc2GIJLFL9-_zsTvf6N6RktOXGc
file_id = '13LSelzc2GIJLFL9-_zsTvf6N6RktOXGc'
downloaded = drive.CreateFile({'id': file_id})
# print('{}'.format(downloaded.GetContentString()))

In [7]:
correct_twitter_202102 = downloaded.GetContentString()

In [8]:
import numpy as np
import pandas as pd
from io import StringIO

pd.options.mode.chained_assignment = None

In [9]:
tweets = StringIO(correct_twitter_202102)
df = pd.read_csv(tweets, sep='\t')
df.head()

<ipython-input-9-57ca370d2b7d>:2: DtypeWarning: Columns (0,4,5,7,8,9,10,11,12,13,20,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(tweets, sep='\t')

,id,event,ts1,ts2,from_stream,directly_from_stream,from_search,directly_from_search,from_quote_search,directly_from_quote_search,...,retweeted,retweeted_author_id,retweeted_handle,retweeted_follower_count,mentioned_author_ids,mentioned_handles,hashtags,urls,media_keys,place_id
0,1358322479136178177,britney_202102,2022-03-01 09:06:52.403595-05:00,2022-03-01 09:06:52.403595-05:00,True,True,False,False,False,False,...,1.358249e+18,9.325937e+07,briebxrries,1002.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1358323016736796677,britney_202102,2022-01-05 08:34:04.477789-05:00,2022-03-01 09:06:52.398778-05:00,True,True,False,False,False,False,...,1.358189e+18,1.752517e+07,Variety,2669599.0,NaN,NaN,['FreeBritney'],NaN,NaN,NaN
2,1358322996696465409,britney_202102,2022-03-01 09:06:52.399008-05:00,2022-03-01 09:06:52.399008-05:00,True,True,False,False,False,False,...,1.358201e+18,4.035766e+08,Johnnerkell,2650.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1358322976769286151,britney_202102,2022-03-01 09:06:52.399205-05:00,2022-03-01 09:06:52.399205-05:00,True,True,False,False,False,False,...,1.358238e+18,4.429004e+09,PopCrave,880695.0,NaN,NaN,['FramingBritney'],NaN,NaN,NaN
4,1368923802260889606,britney_202102,2022-03-01 07:26:05.505986-05:00,2022-03-01 07:26:05.505986-05:00,True,True,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.shape

(845730, 46)

In [11]:
df.columns

Index(['id', 'event', 'ts1', ' ts2', 'from_stream', 'directly_from_stream',
       'from_search', 'directly_from_search', 'from_quote_search',
       'directly_from_quote_search', 'from_convo_search',
       'directly_from_convo_search', 'from_timeline_search',
       'directly_from_timeline_search', 'text', 'lang', 'author_id',
       'author_handle', 'created_at', 'conversation_id', 'possibly_sensitive',
       'reply_settings', 'source', 'author_follower_count', 'retweet_count',
       'reply_count', 'like_count', 'quote_count', 'replied_to',
       'replied_to_author_id', 'replied_to_handle',
       'replied_to_follower_count', 'quoted', 'quoted_author_id',
       'quoted_handle', 'quoted_follower_count', 'retweeted',
       'retweeted_author_id', 'retweeted_handle', 'retweeted_follower_count',
       'mentioned_author_ids', 'mentioned_handles', 'hashtags', 'urls',
       'media_keys', 'place_id'],
      dtype='object')

In [12]:
def summarize_tweet(df, search_term):
  search_df = df[df['text'].str.contains(search_term, case=False, na=False)]

  # Question 1
  # How many tweets were posted containing the term on each day?
  # Not sure what different between ts1 and ts2
  # Use ts1 for simplifity
  search_df['date'] = pd.to_datetime(search_df['ts1']).dt.date
  tweet_count = search_df.groupby('date').count()['id']
  # return tweet_count

  # Question 2
  # How many unique users posted a tweet containing the term?
  # author_id
  user_count = search_df['author_id'].nunique()
  # return user_count

  # Question 3
  # How many likes did tweets containing the term get, on average?
  # like_count
  search_df['like_count'] = pd.to_numeric(search_df['like_count'], errors='coerce').fillna(0).astype(np.int64)
  avg_likes = search_df[search_df['like_count'] >= 0]['like_count'].mean()
  # return avg_likes

  # Question 4
  # Where (in terms of place IDs) did the tweets come from?
  # Remove NaN value
  # place_id
  place_id = search_df['place_id'].dropna().unique()
  # return place_id

  # Question 5
  # What times of day were the tweets posted at?
  # hour
  search_df['hour'] = pd.to_datetime(search_df['ts1']).dt.hour
  # search_df['tod'] = np.NaN
  # Morning: hour >= 6 and < 12
  search_df.loc[(search_df['hour'] >= 6) & (search_df['hour'] < 12), 'tod'] = 'morning'
  # Afternoon: hour >= 12 and < 18
  search_df.loc[(search_df['hour'] >= 12) & (search_df['hour'] < 18), 'tod'] = 'afternoon'
  # Evening: hour >= 18 and <= 23
  search_df.loc[(search_df['hour'] >= 18) & (search_df['hour'] <= 23), 'tod'] = 'evening'
  # Night: hour >= 0 and < 6
  search_df.loc[(search_df['hour'] >= 0) & (search_df['hour'] < 6), 'tod'] = 'night'
  # return search_df[['id','tod']]

  # Question 6
  # Which user posted the most tweets containing the term?
  # author_id
  most_posted_author_id = search_df['author_id'].value_counts().idxmax()
  # return most_posted_author_id

  # Return all answers
  return tweet_count, user_count, avg_likes, place_id, most_posted_author_id, search_df[['id','tod']], most_posted_author_id

In [13]:
result = summarize_tweet(df, 'music')
result

(date
 2022-01-04      307
 2022-01-05      984
 2022-01-22       15
 2022-03-01    31368
 Name: id, dtype: int64,
 25387,
 94.59509089796168,
 array(['a84b808ce3f11719', 'dd3b100831dd1763', '4dad272dba156a02',
        '67687709552688fe', '3b77caf94bfc81fe', 'fbcefe96d630085b',
        '011a05612b6a331c', '3448f4f82d2187bc', '8173485c72e78ca5',
        '0973e42f69d07b84', '016ea1445db12efb', '92e012db736d72c5',
        'c184b698ed4cd4fc', 'a592bd6ceb1319f7', '19ad277db0586bb7',
        '5c2b5e46ab891f07', '75965f8c6ee9a4b0', 'fbd6d2f5a4e4a15e',
        '7cb7440bcf83d464', '9c1c0a45346f5837', 'e81d7291bd2ba45e',
        'ea679934779f45c7', '4ec01c9dbc693497', '0a7dc9891a02c366',
        'fa3435044b52ecc7', '5c62ffb0f0f3479d', '011add077f4d2da3',
        '00dba980404fa58a', '2335250557ea3fb4', '300bcc6e23a88361',
        '48ad377ff2ff9e51', 'c0b8e8dc81930292', '5d058f2e9fe1516c',
        '38d5974e82ed1a6c', '59612bd882018c51', 'e4a0d228eb6be76b',
        'dc234665a759a05d', '7dde0febc9ef245b', '9807c5c5f7a2c6ce',
        '0509a6acb3d27ec4', '25ddf20e1bfb00ea', '3f871475c095f94f',
        '002e24c6736f069d', '6e276f099bcab5b5', '5a110d312052166f',
        '7dea5f8c907d1ea2', 'c8022ca5114d7ea9', '1df98ab7679917e7',
        'fa8e38be72982a5a', '0112bdb03ace5ee9', 'a612c69b44b2e5da',
        'efb544e303ed138c', 'd13775d10c08f835', 'b49b3053b5c25bf5',
        '3b98b02fba3f9753', '4393349f368f67a1', '02f09c87dcbecdb5',
        '62619a76134ad05e', '8004d2bebcc13e8c', 'ad815dfe8c34a012',
        'f5b2e1c998aab0b5', '5f73d127c7ccf9d9', 'dce44ec49eb788f5',
        '01fbe706f872cb32', '01a9a39529b27f36', 'd2981a0f3d8eddd7',
        '5722ff20ba67083b', '005de1fe214f002d', '1d9a5370a355ab0c',
        '01864a8a64df9dc4', 'b2e39072b9847c46', '174309ec90de94d0',
        '68482982f9baf37a', 'c355c3620352b971', '1ef1183ed7056dc1',
        '70392b0b6ad1f95b', '53504716d445dcad'], dtype=object),
 118301422.0,
                          id      tod
 5       1358322956322050051  morning
 70      1368923811211485184  morning
 136     1376753351958880258  morning
 264     1376419087862075392  morning
 287     1376722069510107143  morning
 ...                     ...      ...
 845639  1344979925309255680  morning
 845655  1344962056957661184  morning
 845666  1344958465794404353  morning
 845679  1344874045175697408  morning
 845712  1344878595890675712  morning

 [32674 rows x 2 columns],
 118301422.0)